# Generated by Django 2.1.3 on 2019-01-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvd', '0002_auto_20190105_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='affected_version',
            field=models.CharField(blank=True, max_length=255, verbose_name='Affected Version'),
        ),
    ]
