# Generated by Django 2.1.3 on 2019-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvd', '0003_auto_20190105_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='attack_vector',
            field=models.CharField(blank=True, max_length=255, verbose_name='Attack Vector'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='base_score',
            field=models.FloatField(blank=True, default=0, verbose_name='Base Score'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cwe_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='CWE Type'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='last_modified_date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last Modified Date'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='published_date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vendor Name'),
        ),
    ]
