# Generated by Django 2.1.3 on 2019-01-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvd', '0004_auto_20190105_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('service', models.CharField(blank=True, max_length=30, verbose_name='Service')),
                ('vulnerable_products', models.CharField(blank=True, max_length=255, verbose_name='Vulnerable Products')),
                ('workaround', models.TextField(blank=True, max_length=1000, verbose_name='Workaround')),
                ('permanent_measures', models.TextField(blank=True, max_length=1000, verbose_name='Permanent Measures')),
                ('policy', models.TextField(blank=True, max_length=1000, verbose_name='Policy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vulnerabilities', to='nvd.Vulnerability', verbose_name='Vulnerability')),
            ],
        ),
    ]
